//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinero.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.SourceEntities = new HashSet<SourceEntity>();
            this.UserCompanies = new HashSet<UserCompany>();
        }
    
        public byte Id { get; set; }
        public string Name { get; set; }
        public Nullable<byte> ParentCompanyId { get; set; }
    
        public virtual ICollection<SourceEntity> SourceEntities { get; set; }
        public virtual ICollection<UserCompany> UserCompanies { get; set; }
    }
}
