//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinero.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public long Id { get; set; }
        public int SourceEntityId { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public byte TransactionTypeId { get; set; }
        public decimal Amount { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual SourceEntity SourceEntity { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
